<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f8514477-201c-4e6c-af62-c457ebbcf7ac</testSuiteGuid>
   <testCaseLink>
      <guid>0c3bd02d-d1ad-4b33-b251-5198dd129e7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 01 - LoginBerhasil</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2fc97e14-f06b-4f29-a863-be924ae20aaf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/testdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2fc97e14-f06b-4f29-a863-be924ae20aaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>9239d41a-6f38-491d-8472-111e8b6fb5b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2fc97e14-f06b-4f29-a863-be924ae20aaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>9867debb-998d-49d0-a0d3-b9e61ab63ed6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2fc97e14-f06b-4f29-a863-be924ae20aaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8e47f235-e914-42e7-b987-b2d5c9931e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2fc97e14-f06b-4f29-a863-be924ae20aaf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>deskripsi</value>
         <variableId>43854efa-c416-4df0-801d-f7d3e94800f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9857fdf3-3011-405b-bf0d-df2e5d9a49e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 02 - AddLogbook</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea1d40b-7771-4633-9309-1a7c14eb0225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1633f975-38e3-48c2-bb8d-77d14b4f44ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d49492bd-181f-4587-8c09-1566541cafd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1237fa0d-80f3-4d85-bece-6242e60288ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 03 - AddLogbook Empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd08b22c-bce2-49a4-a502-4146b0c6f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce716b5-ac2d-420e-af2f-b9c5ac10bda9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4a154c5-c109-4878-ae2b-2f0280921017</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
