<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Vision Sharing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ff0f0e8a-1258-4aaf-bb22-3e4c4e82dd42</testSuiteGuid>
   <testCaseLink>
      <guid>beff2bc9-dbcc-4e77-974c-423b7b39be35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 01 - LoginBerhasil</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f5d3c183-5fa9-48e1-bb2a-06df39061a3b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/testdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f5d3c183-5fa9-48e1-bb2a-06df39061a3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>9239d41a-6f38-491d-8472-111e8b6fb5b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f5d3c183-5fa9-48e1-bb2a-06df39061a3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>9867debb-998d-49d0-a0d3-b9e61ab63ed6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f5d3c183-5fa9-48e1-bb2a-06df39061a3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8e47f235-e914-42e7-b987-b2d5c9931e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f5d3c183-5fa9-48e1-bb2a-06df39061a3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>deskripsi</value>
         <variableId>43854efa-c416-4df0-801d-f7d3e94800f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31e1a39f-0584-43a2-8eb6-4bbf0754e559</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 02 - AddLogbook</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea1d40b-7771-4633-9309-1a7c14eb0225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1633f975-38e3-48c2-bb8d-77d14b4f44ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d49492bd-181f-4587-8c09-1566541cafd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5cb4103-0daa-41e6-ab7a-4a8ceb436bb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 03 - AddLogbook Empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd08b22c-bce2-49a4-a502-4146b0c6f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce716b5-ac2d-420e-af2f-b9c5ac10bda9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4a154c5-c109-4878-ae2b-2f0280921017</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83863db8-7bb4-4781-867c-8ed8d4a57680</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 04 - Update Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e20f88b3-bafd-4230-a221-395618c467cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8afbcaaa-7f28-45d2-b0cb-c4d339df118c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce555c38-c506-4bd2-944c-586ccaf5c63d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab6ab43d-f2b3-4460-8ccb-dc7943f3466c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 05 - Searching Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b146e829-30f2-4419-ba7f-167670fca2cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0207399c-0ea7-49f5-8f28-b6c6738143cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f60d3f4-88c6-46f9-b2c8-29a751b5156c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>139e2113-4e70-40dd-b887-0c9ad55a6fe0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e048bdb0-1e1f-40d3-a15c-7dc10eba93ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 06 - Delete Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79aadd0e-047a-426a-b7cd-ea9d80073c5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8f3d736-571b-4d98-aa20-b9b9bf5b1d0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f15524c-38c1-4cda-a051-e50126384765</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1e3e2c5-1bb5-43db-af68-a546d6f7fa12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c69b4e30-2f8b-4b23-8384-a6714261dbc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC - 07 - Delete All Item</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>560ec9d6-6654-4437-80c4-03bd0d07cc2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d98d69-10c0-45a6-b819-1e491cd040e3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
